[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dragonfly = { path = "../../" }
env_logger = "0.10.0"
raqote = "0.8.3"
tokio = { version = "1.32.0", features = ["full"] }

